apiVersion: v1
data:
  hello.sh: |-
    #!/bin/sh -e
    echo "This job's script just wait for 10 times"
    i=1; while [ ${i} -le 10 ]; do
    echo "Wait ${i}"
    sleep 2    
    i=$(( i + 1 ))
    done
    echo "Done"
kind: ConfigMap
metadata:
  name: scripts

---

apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["./scripts/hello.sh"]
        volumeMounts:
          - name: "scripts"
            mountPath: "./scripts/hello.sh"
            subPath: "hello.sh"
      restartPolicy: Never
      volumes:
        - name: "scripts"
          configMap:
            name: "scripts"
            defaultMode: 0777